### ISSUE TITLE
Define in Swagger-UI and generate into Restler? (noob question)

### ISSUE THREAD

**Issue by drmikecrowe** [Luracast/Restler#413]
Hi folks, Just starting with both swagger and restler.  

Is it possible to swagger codegen (or another tool) to generate my Restler classes?

**Comment by RVN-BR** [comment]
You mean like a "visual creation tool"? nope, nothing like that in restler...  Its very easy to create restler classes though... I wouldnt go with something visual which will put more overhead on it all, etc...  In the end you will find after you create the first class you are much faster just cloning off a template....

If you really want something visual you may want to look into Apigility from the guys of Zend Framework... I havent used it... its much younger than Restler, and the download package weighs in at 110mb compressed!!!  I'm not sure I'm that lazy in order to really need to type into a web ui, instead of into a text editor... its really the same info, etc... you could potentially also convert an api class quite easily from Restler to Apigility as the source isnt that different... in the end both are php with a return (althugh apigility isnt caputring the return outside the class like restler (much cleaner and allows code reuse), apigility you need to return using their own wrappers)...

**Comment by drmikecrowe** [comment]
I think it's more of a question of API first.  Using Swagger UI to design
your API, the move to coding next (rather than using Swagger to document
your API from your code).

My problem:

   - I have a fairly large application (embedded as a module in an old CMS)
   that I want to modernize
   - Using something like Swagger UI, define a REST API for how to expose
   the core functionality of the application (rather than hard-coded to the
   old CMS).  For instance, a macro which gets the data for a datatable needs
   a REST call to get paged data from this transaction table.
   - Generate the code for the classes from the resulting Swagger JSON

Or am I missing something?  Are the tools not there quite yet to achieve
this?

**Comment by RVN-BR** [comment]
I'm failing to see how you would "define rest api" "using something like Swagger UI"...

The way it works is basically this... Swagger UI takes a JSON and "shows it pretty in html"... you cant define an api in swagger... you can see a visual representation of a JSON or a restler class phpdoc...

I went through a similar path a while back... We built hundreds (thousands?) of API methods from a legacy web app...  A lot of planning went into it... not a lot of buzz techs such as "API first" or whatever... basically what we did at the time was design the required objects and methods from those, based on the existing system... so for example, the existing system had a Users section... well, that maps out quite well onto a Users object, and method for manipulation... And like that a legacy spaghetti-coded, non-mvc, no-template, php+html mixed in one, non-ajax, non-realtime app, became APIs...

Today we are going into our second iteration of the frontend apps, and the API is just evolving...

My initial version was on paper of teh main items, I then went into Word (yeah, for no particualr reason), and for each object/class started to describe the main methods etc and document what would be inputs (reqiuest) and outputs (response)...  After a few methods other ppl in my team could help by looking at the legacy app and helping to map out onto the new structure...

after everything was "mapped", it was quite quick to change all of that to API classes...  The doc had most comments and fields etc, so it was mostly copy/pasting into php files as doc blocks (restler format, which can also be rendered in swagger)...

But the "human" aspect of looking at your app and planning on paper is the most important, hardest, and less automatable... I dont think you will find anything will help much... would I have liked a wizard-like interface asking me questions (object/class name, method name, method function, expected parameters, etc) instead of a word document? maybe... it could have made things a bit prettier... but honestly once I got started I bet I was quicker on my word template...

With time we ended up pasting mockups of the system that would access the APIs on this same doc, right above the method description, and right below it we would paste real-output from the restler api as each method was coded.  This was before restler had swagger support and it served as our first API documentation....

I hope my account helps in some way to de-mithify the difficulty of approaching an api construction like you describe...  Plan ahead and review along the way... We reviewed and overhauled our authentication scheme the most... ymmv... We kept the API and the legacy system compatible for a long time, and then discontinued the legacy system.

**Comment by drmikecrowe** [comment]
On Fri, Feb 27, 2015 at 11:18 AM, RVN-BR <notifications@github.com> wrote:

> But the "human" aspect of looking at your app and planning on paper is the
> most important, hardest, and less automatable


I guess I thought http://editor.swagger.io/ was the "new way" of doing this
process, and that these new tools helped automate this process.

Thanks for the detailed explanation, I now understand!

**Comment by Arul-** [comment]
@drmikecrowe It is possible, but the templates are not there yet! If there is enough interest we can look into working on a (mustache) template that generates restler php api classes

**Comment by RVN-BR** [comment]
Hi @drmikecrowe sorry I had missed the editor... the yaml is basically just another format... like arul mentioned a template to generate phpdocs from yaml is totally possible... nonetheless, I found the format was less of an issue.

good luck

**Comment by Arul-** [comment]
we will re-visit this after updating Explorer to fully support Swagger 2.0
