### ISSUE TITLE
Swagger Explorer Restler Oauth

### ISSUE THREAD

**Issue by codemonkeyneo** [Luracast/Restler#458]
Just wondering how can I enable Oauth2 testing in the Restler swagger implementation.

I have added 

    <script src='lib/swagger-oauth.js' type='text/javascript'></script>

Into explorer/index.html.

But was wondering what else is required ... 

The API's have all been tested and have the class @oauth2 attributed to them 

    @class  OAuth2 

Which works when tested with OAUTH2 applications we have built.

Any help appreciated , thanks.

**Comment by Arul-** [comment]
Explorer in v3 RC6 (targeting swagger 1.2 spec) is not supporting OAuth yet!
We haven't completed the swagger 2 implementation yet, you can follow the development in features/swagger2 branch. Once that feature is complete, you should be able to authenticate using OAuth2 in the explorer.

Since you are already successful in implementing it, you should be able to help us accelerate the process. You can share a sample implementation that works to begin with :+1:

**Comment by Arul-** [comment]
Re-open this issue when you are ready to share what you have tried
