### ISSUE TITLE
Don't die after respond?

### ISSUE THREAD

**Issue by pzhuchkov** [Luracast/Restler#463]
Hi, we migrated our application on symfony framework. And faced with the fact that in a method respond(), called echo and exit. But according to the rules you need to return an Response object. Can I return the result from respond()?

change from:

```php
echo $this->responseData;
$this->dispatch('complete');
exit;
```

to:

```php
$this->dispatch('complete');
return $this->responseData;
```
and in handle():
```php
return $this->respond();
```

**Comment by Arul-** [comment]
Restler is a bit different, there is no response object.  What is returned by your api class is then sent to Composer class for the structure and then sent as the response. If you need to handle the response globally you can write your own Composer class by implementing iCompose interface

**Comment by beono** [comment]
@Arul- , I think topicstarter asks if there any reason to call `exit` in the end of the respond method.

    // /Luracast/Restler/Restler.php
    protected function respond()
    {
        ...
        echo $this->responseData;
        $this->dispatch('complete');
        exit;
    }

I want to work with Restler this way:

    public function indexAction(Request $request)
    {
        $data  = $this->restler->handle();
        return new JsonResponse($data);
    }

but i can't, because Reslter calls exit and execution of my indexAction is interrupted.
If you don't mind, I can create pull request which will have additional ability to switch off this behaviour.

**Comment by Arul-** [comment]
@beono I can see value in returning the response for the purpose of testing, is there any other use case you can think of?

**Comment by beono** [comment]
@Arul- , my general case is to get symfony controller finished gracefully. When Restler calls `exit` it makes impossible Symfony to do some logging tasks and trigger events. I wish Restler would return the data instead of sending it by using `echo` statement.

**Comment by Arul-** [comment]
@beono You can submit a pull request to v3 branch adding a static property in `Default` class, say `returnResponseData` with the default value `false`. Let `Restler` class check this value and change its behaviour to return the response data instead of echo and exit

```php
Defaults::$returnResponse = true; //$r->handle() will return the data instead of echo and exit
```

**Comment by beono** [comment]
@Arul- , what do you think is the proper place for 'complete' event?

Now, it is triggered before calling exit.
```php
    // Defaults::$returnResponse === false
    echo $this->responseData;
    $this->dispatch('complete');
    exit;
```

But is it correct to trigger this event when we returning the response?

```php
    // Defaults::$returnResponse === true
    $this->dispatch('complete');
    return $this->responseData;
```

Maybe it's better to avoid triggering this event, because it can lead to unexpected results (when using Defaults::$returnResponse === true)

And we can throw an exception if developer is trying to listen to this event 

```php
    Defaults::$returnResponse = true;
    $restler->on(['complete' => ...]); \\ throws \LogicException
```

**Comment by beono** [comment]
@Arul- , please answer

**Comment by Arul-** [comment]
@beono How about a different approach from what we discussed so far

Let `handle` method take an optional parameter 

```php
public function handle($callBackFunction = null)
```

when set `callBackFunction` will be called with the response value and `exit` won't be called

**Comment by kschu91** [comment]
I created a Pull-Request for this: https://github.com/Luracast/Restler/pull/502
