### ISSUE TITLE
HumanReadableCache should check amount of written data

### ISSUE THREAD

**Issue by devbazilio** [Luracast/Restler#492]
I encountered a serious error when partition with framework was run out of space and HumanReadableCache with file_put_contents created incompleted damaged file with routes cache. Next reading of this damaged file cause all framework initialization failure.
So we should always check total amount of written data and delete incomlpete files.
If we try to parse damaged routes file the framework shoud not fails.

**Comment by Arul-** [comment]
This is an edge case. We currently throw an exception when file_put_contents returns zero. Adding code to take care of this rare use case is just going to tax the server.

We think it is the responsibility of the developer to make sure enough space is there! 

But thanks to you, we will document it so that anyone who is wondering why their routes are failing can check for it as a potential cause!
