### ISSUE TITLE
Latest composer release is 3.0.0, not 3.0.0-RC5 or RC6

### ISSUE THREAD

**Issue by JohnMaguire** [Luracast/Restler#512]
FYI, composer versioning sees "3.0.0" as a later version than "RC5" or "RC6", so it's impossible to update to them.

See packagist: https://packagist.org/packages/luracast/restler

**Comment by igorsantos07** [comment]
It's hard to understand what's going on. 3.0 is supposed to be stable, but there's a lot of bugs in the Explorer. The readme is about RC5, but we are on RC6 already (?)

**Comment by Arul-** [comment]
version 3.0.0 should be pointing to latest stable release which is RC5

RC6 is stable enough in every aspect except it requires some tweaks in Explorer. Aim is to get swagger 2.0 support for explorer, but there were some issues with Swagger 2 when we were checking. So we waited for it to fixed. Since it's a moving target we need to check again to see if it's fixed, will do!

**Comment by Arul-** [comment]
As you can see RC5 and 3.0.0 both are pointing to 1dcf910

If you want to use RC6 for your project all you need to do is use "3.0.0-RC6" for the version!

**Comment by igorsantos07** [comment]
So, the issues with the Explorer is based on Swagger issues? That's bad :(
Hope things get sorted out! I'll probably be downgrading to an older
version so the Explorer gets "presentable" to clients.

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]
