### ISSUE TITLE
Another issue with @properties

### ISSUE THREAD

**Issue by infabo** [Luracast/Restler#538]
If this annotation is used, the listed properties are only checked for existence - but not for their type anymore.
Say I provide a string for the toggle attribute, but it should be a bool. It throws no validation error anymore.

``` php
class ActivityData
{
    /**
     * @var string {@from body} {@min 1} {@max 200}  {required false}
     */
    public $title;

    /**
     * @var bool {@from body}  {required false}
     */
    public $toggle;
}
```

``` php
class Test
{
    /**
     * @param string $uid {@min 32} {@max 32}
     * @param ActivityData $data {@from body}{@properties title,toggle}{@required title}
     * @url PUT /activity/:uid
     */
    public function doPut($uid, ActivityData $data)
    {
      // ...
    }
    // ...
```

**Comment by tallsam** [comment]
+1 iValueObject->__set_state() only checks for existence, it never sends the properties for validation.

**Comment by Arul-** [comment]
In order to test this, I have modified in RC6 

https://github.com/Luracast/Restler/blob/master/public/tests/param/Type.php

by adding the `@properties` and `@required` this creates an example very similar to yours

```php
/**
     * Custom class parameter
     *
     * @param Author $author {@properties name,email}{@required name}
     *
     * @return Author
     */
    function postAuthor(Author $author)
    {
        return $author;
    }
```

And added a test in a652de64768dccfda20dec04e2012f46f2a20e82

This makes sure the request fails when I send a valid email but too small name 

RC6 seems to be fine, may be due to the recent commits

I'm closing this issue, for now, please reopen if you still find it unresolved
