### ISSUE TITLE
Update base branch

### ISSUE THREAD

**Issue by richardeaxon** [Luracast/Restler#644]
Is it possible to update the base when you land on the project to the v3 branch? (in Github goto setting/branches/default branch). If you land on the project on Github the master branch makes the project look abandoned. You kinda need to know to specifically use v3 branch if you are not using composer or are a dev.

Perhaps also update the Readme.md on the v3 branch to reflect v3.1.0 and not RC5.

Thanks for the great work btw.

**Comment by Arul-** [comment]
Let me see how to do that!

Btw, there is a newer and better version of Restler brewing at https://github.com/Arul-/reactive-restler check it out!

**Comment by richardeaxon** [comment]
Interesting. I downloaded but not sure how to run and also cannot get composer to complete on my test system as I have too little memory for all the dependencies. I did run phpstan against the code and do notice quite a number of undefined variables.

Try:
php composer.phar require --dev phpstan/phpstan
vendor/bin/phpstan analyse src/

**Comment by Arul-** [comment]
@richardeaxon Thanks. All the issues reported by **phpstan** are resolved now! Give it a try. Once you run `composer install` you can run `composer serv` to run it on PHP dev server. You may also run the tests on another window using `composer test`

**Comment by igorsantos07** [comment]
The master branch is still outdated and still seems that v3 is unstable. Here are some of the questions I'm facing as an end-user:
- I have no clue when v3 went stable, nor what is the project's history without fiddling with git (i.e. if I'm severely outdated or if the project is simply stale). Right now, it seems like an abandoned project. Even the v3.1.1 branch still shows docs for RC5.
- The web references also reflect the same. All web references are outdated, pointing to RC versions, and also looking quite dated on themselves.
- I can't find the docs anywhere??? There are no references to it (that I could find through skimming), be it the new or old README, google, the Luracast pages referencing Restler... Turns out I have to go to "live examples" and navigate from there - I'm not looking for examples, I'm looking for a specific doc about a param.
- is v2 still in use? If so, why? Legacy support, or were there breaking changes? Why is it still referenced everywhere as a "reliable version"?
- docs seems to suggest... downloading the package and then installing it with composer? Is that to use Restler for development, or to develop Restler itself?

Bottom-line: documentation and references are _very confusing_ right now from the point of view of a user.
Please, show some love for the users as well and help us with cleaner documentation and references :)

IIRC I think even submitted an issue a while ago and it got rejected because it was "fixed in v3". I was even writing this thinking I was still on v2... but turns out I'm at 3.0.0. I guess I'll have to take some time to review the issues I've had and re-submit them.

**Comment by Arul-** [comment]
You are right @igorsantos07 I need to spend some time cleaning up the documentation and bring the latest restler currently located at https://github.com/Arul-/reactive-restler to this repository

**Comment by Arul-** [comment]
@richardeaxon @igorsantos07 I'm happy to report Restler is moving ahead again!

 - Restler version 3 RC5 is promoted as Restler 4 now!
 - Restler version 3 RC6 is promoted as Restler 5 now!
 
 Both versions are made compatible with the latest PHP versions. Updated the documentation and set up the live examples

Please check it out.

**Comment by Arul-** [comment]
@igorsantos07 Your write-up helped me a lot to understand where we lack! Please bear with us and help us improve!

>  I have no clue when v3 went stable, nor what is the project's history without fiddling with git (i.e. if I'm severely outdated or if the project is simply stale). Right now, it seems like an abandoned project. Even the v3.1.1 branch still shows docs for RC5.
The web references also reflect the same. All web references are outdated, pointing to RC versions, and also looking quite dated on themselves.

Badges in GitHub will indicate the latest stable version available. 


>  I can't find the docs anywhere??? There are no references to it (that I could find through skimming), be it the new or old README, google, the Luracast pages referencing Restler... Turns out I have to go to "live examples" and navigate from there - I'm not looking for examples, I'm looking for a specific doc about a param.

All the markdown files in the repository itself should serve as the documentation additionally HTML versions of it exist in what we call live examples. which is named after the original use case but evolved as the full documentation.  Point taken we need to update the naming to avoid such confusion.

> is v2 still in use? If so, why? Legacy support, or were there breaking changes? Why is it still referenced everywhere as a "reliable version"?

I guess you are referring to `Luracast.com`. I will fix that!

> docs seem to suggest... downloading the package and then installing it with composer? Is that to use Restler for development, or to develop Restler itself?

Mainly to do a test drive of restler to try the examples.  For building applications out of it, we have application templates in https://github.com/Luracast/Restler-Application we welcome your edits to the readme to make it clear

> it seems there's a GitHub wiki as well... what's the relation of it with the docs from the project website? Why two separate doc places?

Wiki exits as a community contributed documentation

**Comment by richardeaxon** [comment]
> @richardeaxon @igorsantos07 I'm happy to report Restler is moving ahead again!
> 
> * Restler version 3 RC5 is promoted as Restler 4 now!
> * Restler version 3 RC6 is promoted as Restler 5 now!
> 
> Both versions are made compatible with the latest PHP versions. Updated the documentation and set up the live examples
> 
> Please check it out.

Great work - thanks. Can you please tag 5.0.2 as 5.0.1 ls lagging behind and does not have the required fixes so cannot be installed via composer.

**Comment by Arul-** [comment]
I Will do that along with some documentation improvements

**Comment by richardeaxon** [comment]
> I Will do that along with some documentation improvements

Nice. Glad too see documentation updates. Can you please also document callback events? I really had to dig to find useful information. Here are some web references I found that you responded to which you could perhaps use:

All restler callback events
https://stackoverflow.com/questions/32817889/luracast-restler-3-logging-onrespond
https://stackoverflow.com/questions/28357496/using-restler3-how-to-log-requests-responses
https://stackoverflow.com/questions/31853608/how-to-log-all-requests-in-php-restler-3
https://www.cloudways.com/blog/arul-kumaran-restler-interview/

**Comment by Arul-** [comment]
@richardeaxon thanks for the links! will do that

**Comment by Arul-** [comment]
@richardeaxon  done!

See https://restler5.luracast.com/stages.html
